services:
  gradio-app:
    build: .
    container_name: chessaithon-ai
    ports:
      - "7860:7860"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/app
      - ../libraries/c/chessintionlib:/app/chessintionlib

