name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - 'master'
    paths:
      - 'documentacion/**'

# Sets up permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write # Required to deploy to GitHub Pages
  id-token: write # Required for deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Build steps (same as before)
      - name: Install dependencies
        working-directory: documentacion/chessAIthon-documentation
        run: npm ci
        
      - name: npm build
        working-directory: documentacion/chessAIthon-documentation
        run: npm run build

      # 2. Upload the build artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The directory containing the static files to deploy
          path: documentacion/chessAIthon-documentation/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Wait for the 'build' job to complete
    needs: build 
    steps:
      # 3. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
